import type {
  EquipmentSpec,
  EquipmentType,
  FishSpeciesId,
  FishSpeciesSpec,
  PlantSpeciesId,
  PlantSpeciesSpec,
} from "./types";

export const FISH_SPECIES: Record<FishSpeciesId, FishSpeciesSpec> = {
  guppy: {
    id: "guppy",
    label: "Guppy",
    description: "Colorful, hardy livebearer. Great starter fish.",
    adultSize: 4,
    prefs: { tempMin: 22, tempMax: 28, phMin: 6.8, phMax: 7.8 },
    schooling: 1,
    layer: 1,
    spriteKey: "fish_guppy",
    price: 6,
    baseSpeed: 0.0035,
  },
  neon_tetra: {
    id: "neon_tetra",
    label: "Neon Tetra",
    description: "Iridescent shoaler that prefers soft, slightly acidic water.",
    adultSize: 3,
    prefs: { tempMin: 22, tempMax: 27, phMin: 6.0, phMax: 7.0 },
    schooling: 6,
    layer: 1,
    spriteKey: "fish_neon_tetra",
    price: 4,
    baseSpeed: 0.004,
  },
  betta: {
    id: "betta",
    label: "Betta Splendens",
    description: "Solitary labyrinth fish with stunning fins.",
    adultSize: 6,
    prefs: { tempMin: 24, tempMax: 29, phMin: 6.5, phMax: 7.5 },
    schooling: 1,
    layer: 0,
    spriteKey: "fish_betta",
    price: 18,
    baseSpeed: 0.0025,
  },
  goldfish: {
    id: "goldfish",
    label: "Goldfish",
    description: "Cool-water classic with a huge appetite.",
    adultSize: 18,
    prefs: { tempMin: 16, tempMax: 22, phMin: 7.0, phMax: 8.4 },
    schooling: 1,
    layer: 1,
    spriteKey: "fish_goldfish",
    price: 12,
    baseSpeed: 0.003,
  },
  corydoras: {
    id: "corydoras",
    label: "Corydoras",
    description: "Peaceful armored catfish that scavenges the substrate.",
    adultSize: 6,
    prefs: { tempMin: 22, tempMax: 26, phMin: 6.0, phMax: 7.4 },
    schooling: 4,
    layer: 2,
    spriteKey: "fish_corydoras",
    price: 10,
    baseSpeed: 0.0025,
  },
  angelfish: {
    id: "angelfish",
    label: "Angelfish",
    description: "Tall, graceful cichlid that prefers planted tanks.",
    adultSize: 15,
    prefs: { tempMin: 24, tempMax: 29, phMin: 6.5, phMax: 7.5 },
    schooling: 1,
    layer: 1,
    spriteKey: "fish_angelfish",
    price: 22,
    baseSpeed: 0.002,
  },
  discus: {
    id: "discus",
    label: "Discus",
    description: "Demanding showpiece cichlid that needs pristine water.",
    adultSize: 17,
    prefs: { tempMin: 28, tempMax: 31, phMin: 6.0, phMax: 7.0 },
    schooling: 1,
    layer: 1,
    spriteKey: "fish_discus",
    price: 45,
    baseSpeed: 0.0022,
  },
};

export const PLANT_SPECIES: Record<PlantSpeciesId, PlantSpeciesSpec> = {
  java_fern: {
    id: "java_fern",
    label: "Java Fern",
    description: "Low-light epiphyte with wavy dark leaves.",
    spriteKey: "plant_java_fern",
    price: 5,
    oxygenRate: 0.04,
    nitrateRate: 0.04,
  },
  anubias: {
    id: "anubias",
    label: "Anubias",
    description: "Thick rounded leaves, hardy and slow-growing.",
    spriteKey: "plant_anubias",
    price: 7,
    oxygenRate: 0.03,
    nitrateRate: 0.03,
  },
  amazon_sword: {
    id: "amazon_sword",
    label: "Amazon Sword",
    description: "Broad-leaved background plant — excellent oxygenator.",
    spriteKey: "plant_amazon_sword",
    price: 9,
    oxygenRate: 0.07,
    nitrateRate: 0.06,
  },
  java_moss: {
    id: "java_moss",
    label: "Java Moss",
    description: "Soft fluffy moss carpet — shrimp love it.",
    spriteKey: "plant_java_moss",
    price: 4,
    oxygenRate: 0.025,
    nitrateRate: 0.05,
  },
  vallisneria: {
    id: "vallisneria",
    label: "Vallisneria",
    description: "Tall ribbon grass that sways with current.",
    spriteKey: "plant_vallisneria",
    price: 6,
    oxygenRate: 0.05,
    nitrateRate: 0.05,
  },
};

export const EQUIPMENT_SPECS: Record<EquipmentType, EquipmentSpec> = {
  filter: {
    type: "filter",
    label: "HOB Filter",
    description: "Mechanical + biological filtration. Reduces ammonia & turbidity.",
    spriteKey: "equipment_filter",
    price: 35,
  },
  heater: {
    type: "heater",
    label: "Heater",
    description: "Maintains stable temperature.",
    spriteKey: "equipment_heater",
    price: 18,
  },
  airstone: {
    type: "airstone",
    label: "Air Stone",
    description: "Aerates water, raises dissolved oxygen, makes bubbles.",
    spriteKey: "equipment_airstone",
    price: 8,
  },
  co2_diffuser: {
    type: "co2_diffuser",
    label: "CO₂ Diffuser",
    description: "Boosts plant growth, lowers pH slightly.",
    spriteKey: "equipment_co2",
    price: 30,
  },
  light: {
    type: "light",
    label: "LED Light",
    description: "Photosynthesis driver for plants.",
    spriteKey: "equipment_light",
    price: 25,
  },
};
